name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  codespell:
      name: Check for spelling errors
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Codespell
          uses: codespell-project/actions-codespell@v2.0
          with:
            check_hidden: true
            check_filenames: true
            skip: '*.js, *.map, *.css'
